steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/endorse-api:$_TAG', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/endorse-api:$_TAG']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'endorse-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/endorse-api:$_TAG'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DB_HOST=$$DB_HOST,DB_PORT=$$DB_PORT,DB_USERNAME=$$DB_USERNAME,DB_PASSWORD=$$DB_PASSWORD,DB_DATABASE=$$DB_DATABASE,JWT_SECRET=$$JWT_SECRET'

images:
  - 'gcr.io/$PROJECT_ID/endorse-api:$_TAG'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _TAG: "latest"


